Initialize redux
AymanJabr/Bookstore-CMS pull request #2
Opened 2021-06-07 15:41 UTC by ZawadiSumba66

In this milestone, we initialized redux using store to manage our state, reducers, and actions. We also created the BookList component to display our books and the BookForm for adding new books.

2021-06-07 17:03 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @ZawadiSumba66 and @AymanJabr, great job on this milestone so far :muscle: Great implementation of the BookList container :100: Awesome. Right linter configuration is used :1st_place_medal: 

- Kindly copy the contents of `src/App.js` into `src/components/App.js` and remove the `src/App.js` file
- Let us kindly add example books to the initial state object
- `src/reducers/index.js` combines app-specific reducers. **HINT** This is where combine reducers come in

[Optional]
- Kindly move the src/reducers/store to src/. So it becomes src/store


Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-06-07 17:03 UTC, addod19 commented on src/components/Book.js
> +/* eslint-disable */
Kindly avoid these inline disable linter rules. Kindly remove it

2021-06-07 17:03 UTC, addod19 commented on src/containers/BooksForm.js
> +                <option value="mango">Mango</option> */}
Kindly remove this comment, use git history instead

2021-06-07 17:03 UTC, addod19 commented on src/containers/BooksList.js
> +/* eslint-disable react/prop-types */
Kindly avoid inline disabling rules

2021-06-07 17:03 UTC, addod19 commented on src/reducers/books.js
> +      // let book_to_remove = state.books.filter((book)=> book.id == )
Kindly remove comment, use git history instead

2021-06-07 17:03 UTC, addod19 commented on src/containers/BooksForm.js
> +  console.log(e);
[Optional]
- Let us avoid console.log statements, it slows the application. Kindly create a notification component and render it instead

2021-06-08 08:24 UTC, AymanJabr commented
## We added the Initial state of the books in the reducers/book.js file, as it is the place where the reducer is first initialized.

2021-06-08 09:42 UTC, bellom requested changes
## Hi Team  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-08 09:42 UTC, bellom commented on src/reducers/books.js
> +};
Good work.

Yes, the reducer is first initialized here but in React you can always access the state anywhere in your code, keep in mind reducer is for handling actions.

Kindly improve your code by creating the book example in `src.index.js`

From Pathwright;
![image](https://user-images.githubusercontent.com/31897434/121162540-eb3eeb80-c845-11eb-9520-a44e2e225633.png)

Let's keep to the instructions given on pathwright to reduce time spent on creating CRR, and also we both know it is mandatory for all students.

2021-06-08 11:02 UTC, mimipeshy commented
## STATUS: APPROVED 🥳 👯 
Hello team @ZawadiSumba66 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights
- You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

2021-06-08 11:14 UTC, merged